name: Release and publish

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Retrieve version
        run: echo ::set-output name=tag_name::$(jq -r '.version' package.json)
        id: version
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#  build_and_publish:
#    runs-on: ubuntu-latest
#    environment: default
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14.x'
#          always-auth: true
#          registry-url: 'https://registry.npmjs.org'
#      - run: yarn install
#      - run: yarn build
#      - run: yarn publish --verbose
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - uses: actions/setup-node@v2
#        with:
#          registry-url: 'https://npm.pkg.github.com'
#      - run: npm publish
