name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version from package.json
        run: VERSION=$(echo "`jq '.version' package.json`")
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#  build_and_publish:
#    runs-on: ubuntu-latest
#    environment: default
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#        with:
#          node-version: '14.x'
#          always-auth: true
#          registry-url: 'https://registry.npmjs.org'
#      - run: yarn install
#      - run: yarn build
#      - run: yarn publish --verbose
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#      - uses: actions/setup-node@v2
#        with:
#          registry-url: 'https://npm.pkg.github.com'
#      - run: npm publish
