name: Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn install
      - name: Test
        run: yarn test:ci
      - name: Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Report
          path: report.xml
          reporter: jest-junit
