name: Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

jobs:
  ava:
    name: AVA test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: yarn install
      - run: yarn test
